theme: jekyll-theme-cayman
title: "Very Low Complexity Speech Synthesis Using Framewise Autoregressive GAN (FARGAN) with Pitch Prediction"
description: "Demo Samples"
github:
  is_project_page: false
